name: disnetfin
description: "A personal finance tracking and budgeting app."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  hive_flutter: ^1.1.0
  fl_chart: ^0.66.2
  intl: ^0.19.0
  uuid: ^4.3.3
  flutter_bloc: ^9.1.1
  pocketbase: ^0.24.0
  google_fonts: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
